"""initial schema

Revision ID: b53e72b76661
Revises: 
Create Date: 2026-08-26 21:34:00.450549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b53e72b76661'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schulen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bundesland', sa.String(length=64), nullable=False),
    sa.Column('schulform', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faecher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schule_id', sa.Integer(), nullable=False),
    sa.Column('kuerzel', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('benoetigter_raumtyp', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['schule_id'], ['schulen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('halbjahre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schule_id', sa.Integer(), nullable=False),
    sa.Column('start_datum', sa.Date(), nullable=False),
    sa.Column('end_datum', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('entwurf', 'abstimmung', 'veroeffentlicht', name='halbjahr_status', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['schule_id'], ['schulen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schule_id', 'start_datum', name='uq_halbjahr_schule_start')
    )
    op.create_table('lehrer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schule_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('deputat_wochenstunden', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['schule_id'], ['schulen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raeume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schule_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('typ', sa.String(length=64), nullable=False),
    sa.Column('kapazitaet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schule_id'], ['schulen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zeitslots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schule_id', sa.Integer(), nullable=False),
    sa.Column('wochentag', sa.Integer(), nullable=False),
    sa.Column('start_zeit', sa.Time(), nullable=False),
    sa.Column('end_zeit', sa.Time(), nullable=False),
    sa.Column('ist_pause', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['schule_id'], ['schulen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schule_id', 'wochentag', 'start_zeit', name='uq_zeitslot_schule_tag_start')
    )
    op.create_table('klassen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schule_id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(length=32), nullable=False),
    sa.Column('jahrgangsstufe', sa.Integer(), nullable=False),
    sa.Column('klassenleitung_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['klassenleitung_id'], ['lehrer.id'], ),
    sa.ForeignKeyConstraint(['schule_id'], ['schulen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lehrer_qualifikationen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lehrer_id', sa.Integer(), nullable=False),
    sa.Column('fach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fach_id'], ['faecher.id'], ),
    sa.ForeignKeyConstraint(['lehrer_id'], ['lehrer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lehrer_id', 'fach_id', name='uq_qualifikation_lehrer_fach')
    )
    op.create_table('lehrer_verfuegbarkeit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lehrer_id', sa.Integer(), nullable=False),
    sa.Column('zeitslot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lehrer_id'], ['lehrer.id'], ),
    sa.ForeignKeyConstraint(['zeitslot_id'], ['zeitslots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lehrer_id', 'zeitslot_id', name='uq_verfuegbarkeit_lehrer_zeitslot')
    )
    op.create_table('nutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schule_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rolle', sa.Enum('schulleitung', 'lehrkraft', name='nutzer_rolle', native_enum=False), nullable=False),
    sa.Column('lehrer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lehrer_id'], ['lehrer.id'], ),
    sa.ForeignKeyConstraint(['schule_id'], ['schulen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_nutzer_email')
    )
    op.create_table('stundentafel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fach_id', sa.Integer(), nullable=False),
    sa.Column('jahrgangsstufe', sa.Integer(), nullable=False),
    sa.Column('halbjahr_id', sa.Integer(), nullable=False),
    sa.Column('wochenstunden_soll', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fach_id'], ['faecher.id'], ),
    sa.ForeignKeyConstraint(['halbjahr_id'], ['halbjahre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fach_id', 'jahrgangsstufe', 'halbjahr_id', name='uq_stundentafel_fach_jahrgang_halbjahr')
    )
    op.create_table('gruppen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('klasse_id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(length=64), nullable=False),
    sa.Column('fach_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fach_id'], ['faecher.id'], ),
    sa.ForeignKeyConstraint(['klasse_id'], ['klassen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unterrichtseinheiten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('halbjahr_id', sa.Integer(), nullable=False),
    sa.Column('gruppe_id', sa.Integer(), nullable=False),
    sa.Column('lehrer_id', sa.Integer(), nullable=False),
    sa.Column('fach_id', sa.Integer(), nullable=False),
    sa.Column('raum_id', sa.Integer(), nullable=False),
    sa.Column('zeitslot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fach_id'], ['faecher.id'], ),
    sa.ForeignKeyConstraint(['gruppe_id'], ['gruppen.id'], ),
    sa.ForeignKeyConstraint(['halbjahr_id'], ['halbjahre.id'], ),
    sa.ForeignKeyConstraint(['lehrer_id'], ['lehrer.id'], ),
    sa.ForeignKeyConstraint(['raum_id'], ['raeume.id'], ),
    sa.ForeignKeyConstraint(['zeitslot_id'], ['zeitslots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gruppe_id', 'zeitslot_id', 'halbjahr_id', name='uq_h2_gruppen_kollision'),
    sa.UniqueConstraint('lehrer_id', 'zeitslot_id', 'halbjahr_id', name='uq_h1_lehrer_kollision'),
    sa.UniqueConstraint('raum_id', 'zeitslot_id', 'halbjahr_id', name='uq_h3_raum_kollision')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unterrichtseinheiten')
    op.drop_table('gruppen')
    op.drop_table('stundentafel')
    op.drop_table('nutzer')
    op.drop_table('lehrer_verfuegbarkeit')
    op.drop_table('lehrer_qualifikationen')
    op.drop_table('klassen')
    op.drop_table('zeitslots')
    op.drop_table('raeume')
    op.drop_table('lehrer')
    op.drop_table('halbjahre')
    op.drop_table('faecher')
    op.drop_table('schulen')
    # ### end Alembic commands ###
